services:
  - type: web
    name: zhiyin-run
    runtime: static
    repo: https://github.com/gofish040821/zhiyin-run
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
